### Create student
POST http://localhost:8089/springMVC_app_war_exploded/students
Content-Type: application/json

{
  "name": "Dan"
}

### Delete student by id
DELETE http://localhost:8089/springMVC_app_war_exploded/students/1


### Find all students
GET http://localhost:8089/springMVC_app_war_exploded/students