### Create student
POST http://localhost:8082/log_app_war_exploded/students
Content-Type: application/json

{
  "name": "grgtrbfbfgdbgf"
}

### Delete student by id
DELETE http://localhost:8082/log_app_war_exploded/students/1

### Find all students
GET http://localhost:8082/log_app_war_exploded/students